# Generated by Django 3.1.5 on 2021-03-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0007_comment_comment_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_tit',
            field=models.CharField(default=123, max_length=20, verbose_name='краткий заголовок'),
            preserve_default=False,
        ),
    ]
