# Generated by Django 3.1.5 on 2021-11-01 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0009_auto_20210326_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superduty',
            name='year',
        ),
    ]
