# Generated by Django 3.1.5 on 2021-11-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0010_remove_superduty_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='hash',
            field=models.CharField(default='', max_length=50, verbose_name='hash'),
        ),
        migrations.AddField(
            model_name='people',
            name='ip',
            field=models.CharField(default='0.0.0.0', max_length=15, verbose_name='IP'),
        ),
    ]
