# Generated by Django 3.1.5 on 2021-12-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0011_auto_20211103_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_ip',
            field=models.CharField(max_length=50, verbose_name='ip'),
        ),
    ]
