# Generated by Django 3.1.5 on 2021-01-09 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_year', models.CharField(max_length=50, verbose_name='День года')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.CharField(max_length=10, verbose_name='Фамилия')),
                ('imya', models.CharField(max_length=10, verbose_name='Имя')),
                ('otche', models.CharField(max_length=10, verbose_name='Отчество')),
            ],
        ),
        migrations.CreateModel(
            name='SuperDuty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesyas', models.DateField()),
                ('year', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty.people')),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50, verbose_name='Название')),
                ('day_of_week', models.CharField(max_length=50, verbose_name='День недели')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty.people')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty.calendar')),
                ('super', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty.superduty')),
            ],
        ),
    ]
