# Generated by Django 3.1.5 on 2021-01-10 07:34

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'verbose_name': 'День в году', 'verbose_name_plural': 'Дни в году'},
        ),
        migrations.AlterModelOptions(
            name='month',
            options={'verbose_name': 'Дежурство', 'verbose_name_plural': 'Дежурства'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': 'Сотрудник отдела 41', 'verbose_name_plural': 'Сотрудники отдела 41'},
        ),
        migrations.AlterModelOptions(
            name='superduty',
            options={'verbose_name': 'Ответственный дежурный', 'verbose_name_plural': 'Ответственные дежурные'},
        ),
        migrations.AlterField(
            model_name='month',
            name='day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='month',
            name='day_of_week',
            field=models.CharField(max_length=10, verbose_name='День недели'),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='duty.genre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
