# Generated by Django 3.1.5 on 2021-01-10 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0002_auto_20210110_0734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
