# Generated by Django 3.1.5 on 2021-01-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0004_auto_20210123_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Static',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=100, verbose_name='Посещение')),
            ],
            options={
                'verbose_name': 'Запись посещения',
                'verbose_name_plural': 'Записи посещений',
            },
        ),
    ]
