# Generated by Django 3.1.5 on 2021-03-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0006_article_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_ip',
            field=models.CharField(default=1, max_length=20, verbose_name='ip'),
            preserve_default=False,
        ),
    ]
