# Generated by Django 3.1.5 on 2021-03-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0008_article_article_tit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(auto_now=True),
        ),
    ]
